### ISSUE TITLE
WES data in paper

### ISSUE THREAD

**Issue by lgw2023** [alexcoppe/iWhale#1]
Hi, thanks for your excellent job.
I want to download the WES data from Juvenile myelomonocytic leukemia patient in your paper, but I couldn't find the download link.
Could you tell me where the resource is ?

**Comment by alexcoppe** [comment]
Hi, you can download the paired end raw reads from the two patients from here:
[http://compgen.bio.unipd.it/downloads/jmml-twins.tgz](http://compgen.bio.unipd.it/downloads/jmml-twins.tgz) . They are from the paper [Somatic mutations activating Wiskott–Aldrich syndrome protein concomitant with RAS pathway mutations in juvenile myelomonocytic leukemia patients](https://onlinelibrary.wiley.com/doi/full/10.1002/humu.23399) and the link appears in the Supporting Information file.
